/**
 * Example API
 * example
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';

export class RootGet {
    'hello'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "hello",
            "baseName": "hello",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return RootGet.attributeTypeMap;
    }
}

