openapi: 3.0.0
info:
  title: Example API
  description: example
  version: 0.0.1

servers:
  - url: http://localhost:9999
    description: local stub server

paths:
  /:
    get:
      summary: Hello world
      description: hello
      responses:
        '200':
          description: A JSON array of user names
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RootGet"

  /users/{name}:
    get:
      summary: Hello world
      description: hello
      parameters:
        - name: name
          in: path
          required: true
          description: user name.
          schema:
            type: string
      responses:
        '200':
          description: A JSON array of user names
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UsersNameGet"

components:
  schemas:
    RootGet:
      type: object
      properties:
        hello:
          type: string
          example: "world"
    UsersNameGet:
      type: object
      properties:
        foo:
          type: string
          example: "bar"

